global:
  resolve_timeout: 5m

route:
  receiver: "slack-notifications"
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: "slack-notifications"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/XXXXX/XXXXX/XXXXX"
        channel: "#alerts"
        send_resolved: true
        title: "[{{ .Status | toUpper }}] {{ .Labels.alertname }} on {{ .Labels.instance }}"
        text: >-
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Time:* {{ .StartsAt }}
