groups:
  - name: node.rules
    rules:
      - alert: HighCPUUsage
        expr: (100 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          description: CPU usage > 80% for 2 minutes.
          summary: High CPU usage on {{ $labels.instance }}

      - alert: HighMemoryUsage
        expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100) > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          description: Memory usage > 85% for 2 minutes.
          summary: High Memory usage on {{ $labels.instance }}

      - alert: HighDiskIO
        expr: (sum by (instance) (rate(node_disk_read_bytes_total[5m])) + sum by (instance) (rate(node_disk_written_bytes_total[5m]))) > 5e+06
        for: 2m
        labels:
          severity: warning
        annotations:
          description: Disk I/O > 5 MB/s for 2 minutes.
          summary: High Disk I/O on {{ $labels.instance }}

      - alert: HighNetworkTraffic
        expr: (sum by (instance) (rate(node_network_receive_bytes_total{device!="lo"}[5m])) + sum by (instance) (rate(node_network_transmit_bytes_total{device!="lo"}[5m]))) > 5e+06
        for: 2m
        labels:
          severity: warning
        annotations:
          description: Network traffic (in/out) > 5 MB/s for 2 minutes.
          summary: High Network Traffic on {{ $labels.instance }}
